spring:
  datasource:
    url: jdbc:mysql://localhost/db_hrm?allowPublicKeyRetrieval=true&useSSL=false
    username: dev
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    hikari.connection-timeout: 3000
    hikari.idle-timeout: 600000
    hikari.max-lifetime: 1800000
    hikari.minimum-idle: 10
    hikari.maximum-pool-size: 10

  sql:
    init.mode: always
server:
  port: 3000